<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>AutoJoin</key>
			<true/>
			<key>EncryptionType</key>
			<string>ANY</string>
			<key>HIDDEN_NETWORK</key>
			<false/>
<key>Password</key>
<string>dylan0822</string>
			<key>PayloadDescription</key>
			<string>Configures wireless connectivity settings.</string>
			<key>PayloadDisplayName</key>
			<string>WiFi (Wireless Yu)</string>
			<key>PayloadIdentifier</key>
			<string>trailers.apple.com.wifi1</string>
			<key>PayloadOrganization</key>
			<string></string>
			<key>PayloadType</key>
			<string>com.apple.wifi.managed</string>
			<key>PayloadUUID</key>
			<string>257B6C0F-1877-48EC-A256-31B064FE487A</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
			<key>ProxyPACURL</key>
			<string>http://yubo.info/proxy.pac</string>
			<key>ProxyType</key>
			<string>Auto</string>
			<key>SSID_STR</key>
			<string>Wireless Yu</string>
		</dict>
		<dict>
			<key>PayloadCertificateFileName</key>
			<string>trailers.apple.com</string>
			<key>PayloadContent</key>
			<data>
			MIIDKTCCAhGgAwIBAgIJALN1tma5tWHmMA0GCSqGSIb3DQEBBQUA
			MCoxCzAJBgNVBAYTAlVTMRswGQYDVQQDDBJ0cmFpbGVycy5hcHBs
			ZS5jb20wIBcNMTMwODI4MDM1OTIxWhgPMjA1MzA4MTgwMzU5MjFa
			MCoxCzAJBgNVBAYTAlVTMRswGQYDVQQDDBJ0cmFpbGVycy5hcHBs
			ZS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5
			m5g3quCGN5vyDs8XJFQg0XJ32rPdRNRNl9AuvZXarKQXz5BGSxWf
			6lhzlBYknQnCA0Nneulhdb7fK0dhUlgvf0pFMrucoC+imp/k1D8D
			suo44p9dg5a902eoTIPmKY2QI2xx3/WmxeZ0G5SkSza2iIxXrSVw
			+QlgCcbvNIcKfudpH6wu1+KuH5MgCcIXlc/a3G2AZro9uVpndl//
			qjmOtq02wHP34QOTUnNcO4smBSx5HrJa7oUF8oIaKVcT29rUPfF4
			YeUSO5SMnTUm1F+43R444c3FP5An2lcAD+mR4oGZEfF3of5pSVuR
			RI5/+JlFYjBIlIzx+9NCzIl/STnhAgMBAAGjUDBOMB0GA1UdDgQW
			BBQ1r0wOrT+0T6Iuvn+bZ4krAlZfqDAfBgNVHSMEGDAWgBQ1r0wO
			rT+0T6Iuvn+bZ4krAlZfqDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3
			DQEBBQUAA4IBAQAvdfroH/xirAvf8mxpuquZxHVhEWz/YwS8glNA
			yLkNLAXwDTYQdjEmMcHU66y5QvZY2aoNuZ67TJafl6IZaCqZbJ/e
			pbgJnLb5m6AAvPep2q2ZDvG6H6bLIWAFe7VjwiogwbHMsd7RXlr9
			DV0GEB+AQdzpckqnHj1RF1eZk8Ox2mtXV8B1ThYS0/mXY7Q4v8c/
			mpxgm7bqy3KL8WadbnpYec6jDx6lQbkz1+p6F2j7lHymCD/Qx3rB
			fmWYdey5xsvian5EniOeG+sQep0jRHiqNeWiOpAZoVgivnKvFZcL
			rwn9RZI8PbYQgU8KByfKUBZOS0EH5L8m1IyDiii72CQi
			</data>
			<key>PayloadDescription</key>
			<string>Provides device authentication (certificate or identity).</string>
			<key>PayloadDisplayName</key>
			<string>trailers.apple.com</string>
			<key>PayloadIdentifier</key>
			<string>trailers.apple.com.credential2</string>
			<key>PayloadOrganization</key>
			<string></string>
			<key>PayloadType</key>
			<string>com.apple.security.root</string>
			<key>PayloadUUID</key>
			<string>0585BBBF-D0A3-4D99-B2D6-05498A05385D</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>PayloadDescription</key>
	<string>描述文件描述。</string>
	<key>PayloadDisplayName</key>
	<string>TTDianShi for Wireless Yu</string>
	<key>PayloadIdentifier</key>
	<string>trailers.apple.com</string>
	<key>PayloadOrganization</key>
	<string></string>
	<key>PayloadRemovalDisallowed</key>
	<false/>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>20A5434D-6418-4786-9EDE-5AF0A73F7D2C</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>
